name: Linter Audit
on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - name: Check for Lint and Unpinned GitHub Actions
        run: |
          make ensure-bin-dir
          make install-ratchet
          make lint
